# Utiliser une image Python
FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de l'application
COPY ../src/apps/app_model.py /app
COPY ../data/users.json ./data/users.json
COPY ../src/apps/app_model_models.py /app
RUN mkdir /models
# Définir des variables d'environnement
ENV DAGSHUB_USER_TOKEN = XXX
ENV MONGODB_URI = mongodb://localhost:27017
# Installer les packages Python nécessaires
RUN pip install --upgrade pip
RUN pip install --no-cache-dir python-dotenv fastapi[all] dagshub mlflow==2.17.1 pyjwt cryptography python-multipart uvicorn prometheus-fastapi-instrumentator motor


EXPOSE 8000
# Commande par défaut
CMD ["python3", "app_model.py"]
