apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-folder
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: airflow-dags-folder
  hostPath:
    path: /home/adrien/MLOps_Detection_Anomalies_Acoustiques_Et_Vibratoires_Moteurs_Electriques/airflow/dags