apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-folder
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi