apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-folder
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: data-folder
  hostPath:
    path: "/home/adrien/MLOps_Detection_Anomalies_Acoustiques_Et_Vibratoires_Moteurs_Electriques/data/raw"