apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-folder
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: airflow
    name: data-folder
  hostPath:
    path: "/Users/matthieuclaudel/Desktop/MLE_projet/airflow/data"