apiVersion: v1
kind: Pod
metadata:
  name: test-write-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["echo 'Hello World' > /mnt/test/hello_world.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /mnt/test
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: "/home/adrien/MLOps_Detection_Anomalies_Acoustiques_Et_Vibratoires_Moteurs_Electriques/data/raw"
      type: Directory