#token Secrets
apiVersion: v1
kind: Secret
metadata:
  name: my-token-secret
type: Opaque
data:
  token: YWIxZDA5ZTg4YmM5MTdhY2ZiZTZjYzVhNjhmMTMyMjgwZjMxZDM3NA==
---
#token Secrets
apiVersion: v1
kind: Secret
metadata:
  name: mongodbconnect-secret
type: Opaque
data:
  mongodburi: bW9uZ29kYjovL2FwaTphcGlAbW9uZ29kYi5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L3Byb2R1Y3Rpb24=
---
#Basic authentication Secret
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
type: kubernetes.io/basic-auth
stringData:
  username: api_test
  password: api_test