#token Secrets
apiVersion: v1
kind: Secret
metadata:
  name: my-token-secret
type: Opaque
data:
  token: YWIxZDA5ZTg4YmM5MTdhY2ZiZTZjYzVhNjhmMTMyMjgwZjMxZDM3NA==
---
#Basic authentication Secret
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
type: kubernetes.io/basic-auth
stringData:
  username: ssime
  password: test